examples: add missing imports
Fixes these errors when running "cargo build --example basic":

     Compiling rs_ws281x v0.4.4 (/home/pi/rpi-ws281x-rust)
  error[E0433]: failed to resolve: use of undeclared type `StripType`
    --> examples/basic.rs:15:29
     |
  15 |                 .strip_type(StripType::Ws2812)
     |                             ^^^^^^^^^ use of undeclared type `StripType`

  error[E0433]: failed to resolve: use of undeclared type `ChannelBuilder`
    --> examples/basic.rs:12:13
     |
  12 |             ChannelBuilder::new()
     |             ^^^^^^^^^^^^^^ not found in this scope
     |
  help: consider importing this struct
     |
  1  | use rs_ws281x::ChannelBuilder;
     |

  For more information about this error, try `rustc --explain E0433`.
  error: could not compile `rs_ws281x` due to 2 previous errors

Signed-off-by: Bastian Krause <bst@pengutronix.de>