Cargo.toml: set edition field
When no edition field is specified, cargo assumes "2015".

When building the examples with cargo 1.65.0 fails when running
"cargo build --example basic":

  error[E0432]: unresolved import `rs_ws281x`
   --> examples/basic.rs:1:5
    |
  1 | use rs_ws281x::ChannelBuilder;
    |     ^^^^^^^^^ maybe a missing crate `rs_ws281x`?
    |
    = help: consider adding `extern crate rs_ws281x` to use the `rs_ws281x` crate

  error[E0432]: unresolved import `rs_ws281x`
   --> examples/basic.rs:3:5
    |
  3 | use rs_ws281x::ControllerBuilder;
    |     ^^^^^^^^^ maybe a missing crate `rs_ws281x`?
    |
    = help: consider adding `extern crate rs_ws281x` to use the `rs_ws281x` crate

  error[E0432]: unresolved import `rs_ws281x`
   --> examples/basic.rs:4:5
    |
  4 | use rs_ws281x::StripType;
    |     ^^^^^^^^^ maybe a missing crate `rs_ws281x`?
    |
    = help: consider adding `extern crate rs_ws281x` to use the `rs_ws281x` crate

  For more information about this error, try `rustc --explain E0432`.
  error: could not compile `rs_ws281x` due to 3 previous errors

Setting edition to "2021" fixes these issues.

Signed-off-by: Bastian Krause <bst@pengutronix.de>